version: '3.5'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8500:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - infra

networks:
  infra:
    driver: bridge
