name: Image Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: nodeversion
        run: echo ::set-output name=NODE::$(cat .nvmrc)
      - name: restore Cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
      - name: build
        run: |
          yarn build
          cp package.json dist/package.json
          echo "${{ github.sha }}" > dist/revision.txt
          cd dist
          yarn --production
      - name: zip
        run: |
         cd dist &&  zip -r ../package.zip *
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Send to S3
        run: |
          aws s3 cp ./package.zip s3://lambda-builds.keycap-archivist.com/ka-general-build.zip --storage-class REDUCED_REDUNDANCY --acl private --no-progress
      - name: Deploy Lambda function
        run: aws lambda publish-version --function-name ka_general
